name: documentation
on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up build cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install \
            "mkdocs-git-committers-plugin-2>=0.4.3" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-awesome-pages-plugin>=2.7.0" \
            "mkdocs-htmlproofer-plugin>=0.7.0" \
            "mkdocs-git-authors-plugin>=0.6.4" \
            "mkdocs-git-committers-plugin-2>=0.4.3" \
            "mkdocs-redirects>=1.0"
      - name: Install Insiders build
        env:
          MKDOCS_TOKEN: ${{ secrets.MKDOCS_TOKEN }}
        run: |
          git clone --depth 1 https://${MKDOCS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install -e mkdocs-material-insiders
          cp theme/assets/logo.png mkdocs-material-insiders/material/assets/
          cp theme/assets/stylesheets/custom.css mkdocs-material-insiders/material/assets/
          cp theme/assets/favicon.ico mkdocs-material-insiders/material/assets/
          echo "THEME_DIR=mkdocs-material-insiders/material" >> $GITHUB_ENV
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version